name: Elixir CI

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build --target build --build-arg MIX_ENV=test --tag branchpage:latest .

      - name: Start container
        run: |
          cp .env.dev .env
          docker-compose run -d -e MIX_ENV=test -v /branchpage/deps -v /branchpage/_build --name branchpage web /bin/sh

      - name: Code format
        run: docker exec branchpage mix format --check-formatted

      - name: Code consistency
        run: docker exec branchpage mix credo --strict

      - name: Test
        run: |
          docker exec branchpage mix coveralls.json --umbrella
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

